# Generated by Django 3.0.3 on 2020-03-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('e_date', models.DateField()),
                ('wo_issuedate', models.DateField()),
                ('accepted_by', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
