# Generated by Django 3.0.3 on 2020-05-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('planned_time', models.IntegerField()),
                ('actual_time', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('created_date', models.DateField()),
                ('completed_date', models.DateField()),
                ('remarks', models.CharField(max_length=200)),
                ('isComplete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='employee_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='model_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_type', models.CharField(max_length=5)),
                ('status', models.IntegerField()),
                ('isComplete', models.BooleanField()),
                ('product_name', models.CharField(max_length=50)),
                ('expected_date', models.DateField()),
                ('wo_issue_date', models.DateField()),
                ('accepted_by', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=50)),
                ('custtomer_name', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=200)),
                ('attachments', models.CharField(max_length=50)),
                ('customer_contact', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('amount_spend', models.IntegerField()),
            ],
        ),
    ]
