# Generated by Django 3.0.3 on 2020-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_assigned_work_employee_rating_model_rating_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='customer_contact',
            field=models.CharField(max_length=20),
        ),
    ]
