# Generated by Django 3.0.3 on 2020-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=500)),
                ('work_order_no', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('planned_time', models.IntegerField()),
                ('actual_time', models.IntegerField()),
                ('work_remark', models.CharField(max_length=500)),
                ('submission_remark', models.CharField(max_length=500)),
                ('is_complete', models.BooleanField()),
                ('dependency', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='assigned_work',
        ),
    ]
