# Generated by Django 3.0.3 on 2020-06-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_auto_20200623_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
