# Generated by Django 3.0.3 on 2020-07-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_activity_is_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_rating',
            name='work_id',
        ),
        migrations.RemoveField(
            model_name='model_rating',
            name='work_id',
        ),
    ]
