# Generated by Django 3.0.3 on 2020-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_auto_20200711_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
