# Generated by Django 3.0.3 on 2020-07-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_login_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login_table',
            name='status',
            field=models.IntegerField(),
        ),
    ]
