# Generated by Django 3.0.3 on 2020-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_auto_20200713_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
