# Generated by Django 3.0.3 on 2020-07-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_remove_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
