# Generated by Django 3.0.3 on 2020-07-13 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0013_auto_20200713_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_rating',
            name='date',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='model_rating',
            name='date',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
